2019-08-19 18:08:42,434 file.manager INFO 1.2.0
2019-08-19 18:08:42,434 file.manager INFO Copyright (C) 2003-2010
2019-08-19 18:08:42,434 file.manager INFO   Noriaki Ando
2019-08-19 18:08:42,436 file.manager INFO   Intelligent Systems Research Institute, AIST
2019-08-19 18:08:42,436 file.manager INFO Manager starting.
2019-08-19 18:08:42,436 file.manager INFO Starting local logging.
2019-08-19 18:08:42,440 file.manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-08-19 18:08:44,460 file.ManagerServant INFO Master manager not found
2019-08-19 18:08:44,460 file.LocalServiceAdmin INFO All the local services are enabled.
2019-08-19 18:08:44,464 file.manager INFO Component type conf file: RSNPUnitConnector.conf loaded.
2019-08-19 18:08:44,473 file.ec_base INFO setRate(1000000.000000) done
2019-08-19 18:08:44,473 file.ec_base INFO setRate(1000.000000) done
2019-08-19 18:08:44,473 file.rtobject INFO 1 execution context was created.
2019-08-19 18:08:44,476 file.rtobject INFO Initial active configuration set is default.
2019-08-19 18:08:47,275 file.SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-08-19 18:08:47,275 file.SdoServiceAdmin ERROR type  already exists.
2019-08-19 18:08:56,526 file.ManagerServant INFO Master manager not found
2019-08-19 18:09:08,634 file.ManagerServant INFO Master manager not found
2019-08-19 18:09:20,750 file.ManagerServant INFO Master manager not found
2019-08-19 18:09:32,832 file.ManagerServant INFO Master manager not found
2019-08-19 18:09:38,967 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 18:09:38,967 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1571, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 141, in onExecute
    self._Sock.send(send_data_str)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 18:09:44,921 file.ManagerServant INFO Master manager not found
2019-08-19 18:09:51,191 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 18:09:51,194 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1571, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 141, in onExecute
    self._Sock.send(send_data_str)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 18:09:57,026 file.ManagerServant INFO Master manager not found
2019-08-19 18:10:09,094 file.ManagerServant INFO Master manager not found
2019-08-19 18:10:21,178 file.ManagerServant INFO Master manager not found
2019-08-19 18:10:33,243 file.ManagerServant INFO Master manager not found
2019-08-19 18:10:34,549 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1330, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 117, in onActivated
    self._Sock.connect((self._IPaddress[0], self._Port[0]))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 18:10:34,549 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1571, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspace\RSNPUnitConnector\RSNPUnitConnector.py", line 141, in onExecute
    self._Sock.send(send_data_str)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

2019-08-19 18:10:41,756 file.ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2019-08-19 18:10:41,759 file.ec_worker WARNING ExecutionContext is already stopped.
2019-08-19 18:10:41,760 file.ec_base ERROR Invoking on_shutdown() for each RTC failed.
2019-08-19 18:10:45,338 file.ManagerServant INFO Master manager not found
